# =============================================
#              MODULE IMPORTS
# =============================================

import pandas as pd
import numpy as np
from pathlib import Path
import lightgbm as lgb
import shap

# =============================================
#              FUNCTIONAL MODULE
# =============================================

class GridForecaster:
    def __init__(self):
        current_dir = Path(__file__).resolve().parent
        self.project_root = current_dir.parent.parent
        self.raw_data_dir = self.project_root / 'data' / 'raw_data'
        
    def load_and_harmonize(self, load_file="hourlyLoadDataIndia.csv", weather_file="Northern_Region_Hourly_Weather_2019_2024.csv"):
        load_path = self.raw_data_dir / load_file
        weather_path = self.raw_data_dir / weather_file
        
        # 1. Read load data using 'datetime'
        df_load = pd.read_csv(load_path, parse_dates=['datetime'], index_col='datetime')
        # Rename index to 'Datetime' to cleanly match the weather file structure
        df_load.index.name = 'Datetime'
        
        # 2. Read weather data 
        df_weather = pd.read_csv(weather_path, parse_dates=['Datetime'], index_col='Datetime')
        
        df_load = df_load.sort_index()
        df_weather = df_weather.sort_index()
        
        # 3. Inner merge to align timestamps perfectly
        df = pd.merge(df_load, df_weather[['Northern_Region_Avg_T2M']], left_index=True, right_index=True, how='inner')
        return df
    
    def engineer_features(self, df, load_column):
        """Transforms raw telemetry into a scale-free feature matrix for XGBoost."""
        # 1. Scaler Factor Extraction
        rolling_max = df[load_column].rolling(window=24*30, min_periods=1).max()
        df['normalized_target'] = df[load_column] / rolling_max
        
        # 2. Cyclical Time Transformations
        df['hour'] = df.index.hour
        df['hour_sin'] = np.sin(2 * np.pi * df['hour'] / 24.0)
        df['hour_cos'] = np.cos(2 * np.pi * df['hour'] / 24.0)
        
        df['dayofweek'] = df.index.dayofweek
        df['month'] = df.index.month
        
        # 3. Autoregressive Lag Pipeline
        df['load_lag_1'] = df['normalized_target'].shift(1)
        df['load_lag_2'] = df['normalized_target'].shift(2)
        df['load_lag_24'] = df['normalized_target'].shift(24)
        
        # Drop the edge-case NaNs generated by shifting and rolling operations
        df.dropna(inplace=True)
        return df
    


    def train_quantile_models(self, df):
        """Trains individual LightGBM regressors targeting the 10th, 50th, and 90th quantiles."""
        feature_cols = [
            'hour_sin', 'hour_cos', 'dayofweek', 'month', 
            'load_lag_1', 'load_lag_2', 'load_lag_24', 
            'Northern_Region_Avg_T2M'
        ]
        target_col = 'normalized_target'
        
        # Chronological Validation Split (80% Train, 20% Test)
        split_idx = int(len(df) * 0.8)
        train_df = df.iloc[:split_idx]
        test_df = df.iloc[split_idx:]
        
        X_train, y_train = train_df[feature_cols], train_df[target_col]
        X_test, y_test = test_df[feature_cols], test_df[target_col]
        
        quantiles = [0.10, 0.50, 0.90]
        self.models = {}
        
        for q in quantiles:
            print(f"Training LightGBM Regressor for Quantile: {q}...")
            
            # --- THE LIGHTGBM CORE SYNTAX ---
            # objective must be 'quantile'
            # alpha specifies the exact target percentile
            model = lgb.LGBMRegressor(
                objective='quantile',
                alpha=q,
                n_estimators=300,
                learning_rate=0.05,
                num_leaves=31,
                max_depth=6,
                random_state=42,
                verbose=-1 # Suppresses unnecessary logging noise in terminal
            )
            
            model.fit(X_train, y_train)
            self.models[q] = model
            
            # Serialize model using LightGBM's native save method (.txt pattern)
            model_path = self.project_root / 'models' / f'lightgbm_q_{int(q*100)}.txt'
            model_path.parent.mkdir(parents=True, exist_ok=True)
            model.booster_.save_model(str(model_path))
            
        print("All LightGBM quantile models successfully serialized locally.")
        return X_test, y_test
    
    
    def load_models(self):
        """Loads pre-trained LightGBM models from disk for rapid inference."""
        import lightgbm as lgb
        quantiles = [0.10, 0.50, 0.90]
        self.models = {}
        
        for q in quantiles:
            model_path = self.project_root / 'models' / f'lightgbm_q_{int(q*100)}.txt'
            # Load the text file back into a LightGBM Booster object
            self.models[q] = lgb.Booster(model_file=str(model_path))
            
        print("LightGBM models loaded from disk successfully.")

    
    def forecast_next_hour(self, recent_features, current_grid_baseline_mw):
        """
        Accepts a dictionary of the most recent time, lag, and weather metrics.
        Returns the denormalized true MW capacity bounds for the multi-agent brain.
        """
        # Format input vector into the standard Pandas row shape expected by the model
        X_input = pd.DataFrame([recent_features])
        
        predictions = {}
        for q, model in self.models.items():
            # Generate dimensionless prediction shape [0.0 - 1.2]
            pred_normalized = model.predict(X_input)[0]
            
            # Denormalize target using the specific grid engine configuration profile
            predictions[f"p{int(q*100)}"] = float(pred_normalized * current_grid_baseline_mw)
            
        return predictions

    def explain_prediction(self, recent_features):
        """
        Returns per-feature SHAP contributions for the median (p50) quantile model, 
        so the Decision Agent's operator brief can say WHICH grid factors drove a given forecast 
        - the Explainability Matrix's 'Feature Importance' requirement. 
        Uses the p50 model specifically since it's the single most representative estimate;
        the p10/p90 models would just show the same features driving the spread rather than the central forecast itself.
        """

        if not hasattr(self, "models") or 0.50 not in self.models:
            raise RuntimeError("Call load_models() (or train_quantile_models()) before explaining.")

        X_input = pd.DataFrame([recent_features])
        explainer = shap.TreeExplainer(self.models[0.50])
        shap_values = explainer.shap_values(X_input)

        # shap_values is shape [1, n_features] for a single-row input
        contributions = dict(zip(X_input.columns.tolist(), shap_values[0].tolist()))

        # Sort by absolute magnitude, largest driver first - this is what
        # actually goes in the operator brief, not the raw unordered dict.
        ranked = sorted(contributions.items(), key=lambda kv: abs(kv[1]), reverse=True)

        return {
            "base_value": float(explainer.expected_value),
            "contributions": contributions,
            "ranked_features": ranked,
        }

# ==================================================
#              TESTING & EXECUTION
# ==================================================
# REMARK: For training or fine-tuning the Temporal Fusion Transformer (TFT) on cloud GPUs (e.g., Google Colab/Kaggle),
#         Please use the interactive notebook located at: notebooks/01_TFT_Multi_Horizon_Cloud_Training.ipynb

if __name__ == "__main__":
    # 1. Initialize and Prepare Data
    forecaster = GridForecaster()
    df_harmonized = forecaster.load_and_harmonize()
    df_features = forecaster.engineer_features(df_harmonized, load_column='Northen Region Hourly Demand')


    # EXPORTING DATA FOR CLOUD TFT MODEL (PyTorch)
    print("\nPreparing matrix for PyTorch TFT Export...")
    
    df_cloud = df_features.copy()
    df_cloud['time_idx'] = range(len(df_cloud))
    df_cloud['region'] = 'Northern'
    
    # Route to the processed_data directory
    processed_dir = forecaster.project_root / 'data' / 'processed_data'
    processed_dir.mkdir(parents=True, exist_ok=True)
    
    export_path = processed_dir / 'tft_ready_data.csv'
    df_cloud.reset_index().to_csv(export_path, index=False)
    
    print(f"Success! Cloud-ready dataset exported to: {export_path}")
    
    # 2. Execute Training
    # This will trigger the XGBoost loops and save the .json files to disk
    print("\nStarting Model Training Phase...")
    X_test, y_test = forecaster.train_quantile_models(df_features)
    
    # 3. The Mock Dataset 
    # Simulating a July midnight with high temperature and 85% grid load momentum
    mock_telemetry = {
        'hour_sin': 0.0,
        'hour_cos': 1.0, 
        'dayofweek': 2,  
        'month': 7,      
        'load_lag_1': 0.85,
        'load_lag_2': 0.86,
        'load_lag_24': 0.82,
        'Northern_Region_Avg_T2M': 32.5 
    }
    
    # 4. Generate the Forecast Bounds
    # Passing the mock data and scaling it to a 33,000 MW grid baseline
    bounds = forecaster.forecast_next_hour(mock_telemetry, current_grid_baseline_mw=33000)
    
    print("\n--- Next Hour Predictive Bounds ---")
    print(bounds)